version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: testas-postgres
    environment:
      POSTGRES_DB: testas_db
      POSTGRES_USER: testas_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testas_user -d testas_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: testas-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-dev-redis-password-2024}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD:-dev-redis-password-2024}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data: