#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged to check staged files
npx lint-staged

# Run type checking
npm run type-check

# Run tests related to staged files
npm run test -- --bail --findRelatedTests --passWithNoTests